export const menulists = [
  {
    id: 1,
    path: "/",
    link: "home",
  },
  {
    id: 2,
    path: "/product",
    link: "product",
  },
  {
    id: 3,
    path: "/chat",
    link: "Chat",
  },
  {
    id: 4,
    path: "/about",
    link: "about",
  },
  {
    id: 5,
    path: "/services",
    link: "Services",
  },
  {
    id: 6,
    path: "/contact",
    link: "Contact",
  },
  {
    id: 7,
    path: "/seller-hub",
    link: "Seller Hub",
  }
];

export const categorylists = [
  {
    id: 1,
    image: "../images/category/c1.png",
    title: "electronics",
  },
  {
    id: 2,
    image: "../images/category/c2.png",
    title: "fashion",
  },
  {
    id: 3,
    image: "../images/category/c3.png",
    title: "collectibles",
  },
  {
    id: 4,
    image: "../images/category/c4.png",
    title: "home appliances",
  },
  {
    id: 5,
    image: "../images/category/c5.png",
    title: "sports equipments",
  },
  {
    id: 6,
    image: "../images/category/c6.png",
    title: "toys and games",
  },
  {
    id: 7,
    image: "../images/category/c7.png",
    title: "vehicles",
  },
  {
    id: 8,
    image: "../images/category/c8.png",
    title: "real estate",
  },
  {
    id: 9,
    image: "../images/category/c9.png",
    title: "art and crafts",
  },
  {
    id: 10,
    image: "../images/category/c10.png",
    title: "jewelry and accessories",
  },
  {
    id: 11,
    image: "../images/category/c11.png",
    title: "health and beauty",
  },
  {
    id: 12,
    image: "../images/category/c12.png",
    title: "garden and outdoors",
  },
  {
    id: 13,
    image: "../images/category/c13.png",
    title: "music instruments",
  },
  {
    id: 14,
    image: "../images/category/c14.png",
    title: "pet supplies",
  },
  {
    id: 15,
    image: "../images/category/c15.png",
    title: "office supplies",
  },
];


export const productlists = [
  {
    id: 1,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-7-768x768.png",
    name: "Blown Glass Creations for Every Occasion",
    description: "",
    productStatus: "Open", // Có thời gian còn lại và số lượt đặt giá
    sellerId: "2",
    stockQuantity: "",
    categories: "Arts",
    bprice: 853,
    price: 5000,
    bids: 15,
    timeleft: "2d 4h 30m",
  },
  {
    id: 2,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-8-390x532.png",
    name: "Capturing Nature’s Beauty",
    description: "",
    productStatus: "Open",
    sellerId: "2",
    stockQuantity: "",
    categories: "Arts",
    bprice: 452,
    price: 1420,
    bids: 8,
    timeleft: "1d 6h 12m",
  },
  {
    id: 3,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-1-390x532.png",
    name: "Ceramic Tea Sets with a Twist",
    description: "",
    productStatus: "Closed", // Giá đã đóng
    sellerId: "",
    stockQuantity: "",
    categories: "Arts",
    bprice: 105,
    price: 100,
    bids: 22,
    timeleft: "0d 18h 45m",
  },
  {
    id: 4,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-600x600.jpg",
    name: "Vintage Motorcycles and Scooters",
    description: "",
    productStatus: "Pending", // Sản phẩm còn nhiều thời gian
    sellerId: "",
    stockQuantity: "",
    categories: "Automotive",
    bprice: 40000,
    price: 50000,
    bids: 35,
    timeleft: "5d 3h 24m",
  },
  {
    id: 5,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-02-600x600.jpg",
    name: "Off-Road Adventure Seekers",
    description: "",
    productStatus: "Open",
    sellerId: "",
    stockQuantity: "",
    categories: "Automotive",
    bprice: 4000,
    price: 8000,
    bids: 12,
    timeleft: "2d 5h 15m",
  },
  {
    id: 6,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-04-600x600.jpg",
    name: "Rare Exotics and Supercars",
    description: "",
    productStatus: "Closed",
    sellerId: "",
    stockQuantity: "",
    categories: "Automotive",
    bprice: 40000,
    price: 80000,
    bids: 17,
    timeleft: "0d 10h 0m",
  },
  {
    id: 7,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_07-600x600.jpg",
    name: "Romantic Escapes Collection",
    description: "",
    productStatus: "Pending",
    sellerId: "",
    stockQuantity: "",
    categories: "Romantic Escapes",
    bprice: 400,
    price: 800,
    bids: 4,
    timeleft: "3d 14h 5m",
  },
  {
    id: 8,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_02-600x600.jpg",
    name: "Epic Fantasy Chronicles",
    description: "",
    productStatus: "Pending",
    sellerId: "",
    stockQuantity: "",
    categories: "Romantic Escapes",
    bprice: 200,
    price: 800,
    bids: 10,
    timeleft: "1d 0h 22m",
  },
  {
    id: 9,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/books_demo_product_09-600x600.jpg",
    name: "Graphic Non-Fiction",
    description: "",
    productStatus: "Pending",
    sellerId: "",
    stockQuantity: "",
    categories: "Romantic Escapes",
    bprice: 200,
    price: 800,
    bids: 3,
    timeleft: "0d 23h 30m",
  },
  {
    id: 10,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/coin-auction-demo-product-10-768x768.jpg",
    name: "Coin Hyundai Sonata",
    description: "",
    productStatus: "Cancelled",
    sellerId: "",
    stockQuantity: "",
    categories: "Arts",
    bprice: 853,
    price: 5000,
    bids: 18,
    timeleft: "0d 5h 50m",
  },
  {
    id: 11,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/coin-auction-demo-product-07-768x768.jpg",
    name: "2018 Hyundai Sonata",
    description: "",
    productStatus: "Open",
    sellerId: "",
    stockQuantity: "",
    categories: "Automotive",
    bprice: 853,
    price: 5000,
    bids: 5,
    timeleft: "3d 2h 25m",
  },
  {
    id: 12,
    productImages: "https://netstorm-react.theme-land.com/img/auction_4.jpg",
    name: "2018 Hyundai Sonata - Limited Edition",
    description: "",
    productStatus: "Closed",
    sellerId: "",
    stockQuantity: "",
    categories: "Automotive",
    bprice: 853,
    price: 5000,
    bids: 2,
    timeleft: "2d 0h 15m",
  },
  {
    id: 13,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-1-768x768.png",
    name: "Ceramic Vases with Modern Designs",
    description: "",
    productStatus: "Pending",
    sellerId: "S13",
    stockQuantity: 20,
    categories: "Decor",
    bprice: 450,
    price: 2000,
    bids: 5,
    timeleft: "1d 3h 15m",
  },
  {
    id: 14,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-2-768x768.png",
    name: "Vintage Leather-bound Notebooks",
    description: "",
    productStatus: "Pending",
    sellerId: "S14",
    stockQuantity: 30,
    categories: "Stationery",
    bprice: 150,
    price: 700,
    bids: 3,
    timeleft: "3d 2h 45m",
  },
  {
    id: 15,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-3-768x768.png",
    name: "Handcrafted Wooden Bowls",
    description: "",
    productStatus: "Closed",
    sellerId: "S15",
    stockQuantity: 0,
    categories: "Kitchen",
    bprice: 300,
    price: 1200,
    bids: 8,
    timeleft: "0d 0h 0m",
  },
  {
    id: 16,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-4-768x768.png",
    name: "Luxury Silk Scarves",
    description: "",
    productStatus: "Open",
    sellerId: "S16",
    stockQuantity: 50,
    categories: "Fashion",
    bprice: 500,
    price: 2500,
    bids: 10,
    timeleft: "5d 1h 30m",
  },
  {
    id: 17,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-5-768x768.png",
    name: "Elegant Glass Candle Holders",
    description: "",
    productStatus: "Open",
    sellerId: "S17",
    stockQuantity: 15,
    categories: "Home Decor",
    bprice: 120,
    price: 600,
    bids: 2,
    timeleft: "6d 12h 0m",
  },
  {
    id: 18,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-6-768x768.png",
    name: "Customizable Wall Art Prints",
    description: "",
    productStatus: "Open",
    sellerId: "S18",
    stockQuantity: 25,
    categories: "Art",
    bprice: 800,
    price: 3500,
    bids: 12,
    timeleft: "4d 7h 10m",
  },
  {
    id: 19,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-7-768x768.png",
    name: "Eco-Friendly Tote Bags",
    description: "",
    productStatus: "Closed",
    sellerId: "S19",
    stockQuantity: 40,
    categories: "Accessories",
    bprice: 200,
    price: 800,
    bids: 6,
    timeleft: "2d 22h 5m",
  },
  {
    id: 20,
    productImages: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/nuron-art-demo-image-8-768x768.png",
    name: "Hand-painted Ceramic Mugs",
    description: "",
    productStatus: "Cancelled",
    sellerId: "S20",
    stockQuantity: 35,
    categories: "Kitchen",
    bprice: 250,
    price: 1000,
    bids: 9,
    timeleft: "3d 5h 20m",
  },
];

export const watchlist = [
  {
    id: 1,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 1",
    currentBid: "896.74",
    yourBid: "732.53",
    status: "Out Bid",
    timeLeft: "0d 5h 20m"
  },
  {
    id: 2,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 2",
    currentBid: "432.17",
    yourBid: "489.04",
    status: "Winning",
    timeLeft: "0d 9h 15m"
  },
  {
    id: 3,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 3",
    currentBid: "543.89",
    yourBid: "410.27",
    status: "Out Bid",
    timeLeft: "2d 7h 50m"
  },
  {
    id: 4,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 4",
    currentBid: "687.93",
    yourBid: "620.45",
    status: "Out Bid",
    timeLeft: "4d 6h 30m"
  },
  {
    id: 5,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 5",
    currentBid: "874.12",
    yourBid: "920.34",
    status: "Winning",
    timeLeft: "5d 12h 5m"
  },
  {
    id: 6,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 6",
    currentBid: "678.94",
    yourBid: "736.51",
    status: "Winning",
    timeLeft: "7d 4h 45m"
  },
  {
    id: 7,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 7",
    currentBid: "915.12",
    yourBid: "872.56",
    status: "Out Bid",
    timeLeft: "0d 10h 15m"
  },
  {
    id: 8,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 8",
    currentBid: "412.39",
    yourBid: "326.48",
    status: "Winning",
    timeLeft: "1d 15h 20m"
  },
  {
    id: 9,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 9",
    currentBid: "602.18",
    yourBid: "573.22",
    status: "Out Bid",
    timeLeft: "3d 3h 40m"
  },
  {
    id: 10,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 10",
    currentBid: "538.92",
    yourBid: "497.65",
    status: "Out Bid",
    timeLeft: "4d 2h 30m"
  },
  {
    id: 11,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 11",
    currentBid: "895.17",
    yourBid: "950.23",
    status: "Winning",
    timeLeft: "5d 8h 5m"
  },
  {
    id: 12,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 12",
    currentBid: "603.45",
    yourBid: "522.60",
    status: "Out Bid",
    timeLeft: "1d 6h 0m"
  },
  {
    id: 13,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 13",
    currentBid: "734.67",
    yourBid: "799.13",
    status: "Winning",
    timeLeft: "0d 9h 30m"
  },
  {
    id: 14,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 14",
    currentBid: "536.50",
    yourBid: "460.80",
    status: "Out Bid",
    timeLeft: "0d 5h 25m"
  },
  {
    id: 15,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 15",
    currentBid: "844.23",
    yourBid: "815.62",
    status: "Out Bid",
    timeLeft: "4d 1h 35m"
  },
  {
    id: 16,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 16",
    currentBid: "715.49",
    yourBid: "690.41",
    status: "Winning",
    timeLeft: "1d 7h 50m"
  },
  {
    id: 17,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 17",
    currentBid: "924.89",
    yourBid: "750.60",
    status: "Out Bid",
    timeLeft: "4d 14h 10m"
  },
  {
    id: 18,
    userId: "",
    auctionID: "",
    createdAt: "",
    updatedAt: "",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Auction Item 18",
    currentBid: "513.88",
    yourBid: "465.72",
    status: "Out Bid",
    timeLeft: "1d 11h 5m"
  }
];

export const orders = [
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 1250000,
    paymentDueDate: "2024-12-01",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh sơn dầu phong cảnh"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 2500000,
    paymentDueDate: "2024-12-02",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng Phật cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 3750000,
    paymentDueDate: "2024-12-03",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình gốm thời Lý"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 1800000,
    paymentDueDate: "2024-12-04",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh thêu tay truyền thống"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 4200000,
    paymentDueDate: "2024-12-05",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Đèn lồng cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 3300000,
    paymentDueDate: "2024-12-06",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng đồng nghệ thuật"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 2900000,
    paymentDueDate: "2024-12-07",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Khay trà cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 5100000,
    paymentDueDate: "2024-12-08",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bức tranh thủy mặc"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 1950000,
    paymentDueDate: "2024-12-09",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình hoa gốm sứ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 4800000,
    paymentDueDate: "2024-12-10",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng phỗng đá cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 2750000,
    paymentDueDate: "2024-12-11",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh lụa thêu tay"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 3900000,
    paymentDueDate: "2024-12-12",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bát đĩa cổ thời Nguyễn"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 2200000,
    paymentDueDate: "2024-12-13",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Chậu cảnh cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 5500000,
    paymentDueDate: "2024-12-14",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng Phật bằng ngọc"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 3100000,
    paymentDueDate: "2024-12-15",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh đông hồ cổ"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 4600000,
    paymentDueDate: "2024-12-16",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Ấm trà tử sa"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 2850000,
    paymentDueDate: "2024-12-17",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Đĩa gốm men lam"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 5200000,
    paymentDueDate: "2024-12-18",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng đồng thời Trần"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 3400000,
    paymentDueDate: "2024-12-19",
    status: "Unpaid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình phong thêu tay"
  },
  {
    id: "",
    userId: "",
    auctionId: "",
    totalAmount: 4900000,
    paymentDueDate: "2024-12-20",
    status: "Paid",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh sơn mài cổ"
  }
];

export const payments = [
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX123456789",
    amount: 1250000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-01 09:30:15",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh sơn dầu phong cảnh"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX987654321",
    amount: 2500000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-02 14:45:22",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng Phật cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX456789123",
    amount: 3750000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-03 11:20:33",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình gốm thời Lý"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX789123456",
    amount: 1800000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-04 16:15:45",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh thêu tay truyền thống"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX321654987",
    amount: 4200000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-05 10:05:18",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Đèn lồng cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX654987321",
    amount: 3300000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-06 13:40:27",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng đồng nghệ thuật"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX147258369",
    amount: 2900000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-07 15:55:36",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Khay trà cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX258369147",
    amount: 5100000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-08 08:25:42",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bức tranh thủy mặc"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX369147258",
    amount: 1950000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-09 12:10:54",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình hoa gốm sứ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX741852963",
    amount: 4800000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-10 17:30:11",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng phỗng đá cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX852963741",
    amount: 2750000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-11 09:15:28",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh lụa thêu tay"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX963741852",
    amount: 3900000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-12 14:20:37",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bát đĩa cổ thời Nguyễn"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX159357486",
    amount: 2200000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-13 11:45:49",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Chậu cảnh cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX357486159",
    amount: 5500000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-14 16:50:23",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng Phật bằng ngọc"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX486159357",
    amount: 3100000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-15 10:35:31",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh đông hồ cổ"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX951753684",
    amount: 4600000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-16 13:25:44",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Ấm trà tử sa"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX753684951",
    amount: 2850000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-17 15:40:52",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Đĩa gốm men lam"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX684951753",
    amount: 5200000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-18 08:55:16",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tượng đồng thời Trần"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX246813579",
    amount: 3400000,
    paymentMethod: "",
    status: "Success",
    bankCode: "",
    paymentDate: "2024-11-19 12:30:28",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Bình phong thêu tay"
  },
  {
    id: "",
    orderId: "",
    userId: "",
    transactionId: "TRX135792468",
    amount: 4900000,
    paymentMethod: "",
    status: "Failed",
    bankCode: "",
    paymentDate: "2024-11-20 17:15:39",
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-14.jpg",
    title: "Tranh sơn mài cổ"
  }
];

export const processList = [
  {
    id: "01",
    title: "Sign up",
    desc: "Sign your car up via our contact form or via the WhatsApp chat on the website. Send us a couple of pictures of the car that you want to put up for auction.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/shape-7.png",
  },
  {
    id: "02",
    title: "Auction goes online",
    desc: "As soon as we collect enough cars for the auction (we strive for 25 to 40 cars per auction), the auction will show up on the website.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction.png",
  },
  {
    id: "03",
    title: "Closing auction",
    desc: "After the viewing day(s) the auction is still a few days open for new bids. We evaluate the highest bid after the closing of an auction.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-2.png",
  },
  {
    id: "04",
    title: "The last steps",
    desc: "After the car is sold to the highest bidder, all the cars will be collected by the buyers on a determined date.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-3.png",
  },
];

export const topSellerList = [
  {
    id: 1,
    title: "William",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-5-1.png",
    amount: "100",
  },
  {
    id: 2,
    title: "Orko",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-6.png",
    amount: "200",
  },
  {
    id: 3,
    title: "Nipa",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-3.png",
    amount: "300",
  },
  {
    id: 4,
    title: "Joseph",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-2-2.png",
    amount: "100",
  },
  {
    id: 5,
    title: "Isabella",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-10-2.png",
    amount: "100",
  },
  {
    id: 6,
    title: "Emily",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-15-1.png",
    amount: "100",
  },
  {
    id: 7,
    title: "Devmahbub",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8-3.png",
    amount: "100",
  },
  {
    id: 8,
    title: "Ava Garcia",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-4-1.png",
    amount: "100",
  },
  {
    id: 9,
    title: "Amelia Harris",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-13.png",
    amount: "100",
  },
  {
    id: 10,
    title: "Alexander",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8.png",
    amount: "100",
  },
];

export const trustList = [
  {
    id: 1,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 2,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 3,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor2.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor4.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor5.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor6.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor7.png",
  },
  {
    id: 8,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 9,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
  {
    id: 10,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
];

export const topList = [
  {
    id: 1,
    catgeory: "Luxury Vehicles",
    total: 7,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-08-150x150.jpg",
  },
  {
    id: 2,
    catgeory: "Classic",
    total: 10,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-09-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
  },
  {
    id: 3,
    catgeory: "Muscle Machines",
    total: 8,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-150x150.jpg",
  },
  {
    id: 4,
    catgeory: "Automotive",
    total: 4,
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-05-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-05-768x768.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-04-768x768.jpg",
  },
];
